// Generated by CoffeeScript 1.9.1

/*
This is separate Jade template for Clinch processor
 */

(function() {
  var JADE_SETTINGS, Jade, _, builder, extension, processor;

  Jade = require('jade');

  _ = require('lodash');

  extension = '.jade';

  JADE_SETTINGS = {
    pretty: true,
    self: true,
    compileDebug: false
  };

  processor = function(data, filename, cb) {
    var content, error;
    try {
      content = Jade.compileClient(data, _.assign({}, JADE_SETTINGS, {
        filename: filename
      }));
    } catch (_error) {
      error = _error;
      return cb(error);
    }
    return cb(null, "module.exports = " + content);
  };

  builder = function(options) {
    return {
      extension: extension,
      processor: function(data, filename, cb) {
        var content, error;
        try {
          content = Jade.compileClient(data, _.assign({}, JADE_SETTINGS, options, {
            filename: filename
          }));
        } catch (_error) {
          error = _error;
          return cb(error);
        }
        return cb(null, "module.exports = " + content);
      }
    };
  };

  builder.extension = extension;

  builder.processor = processor;

  module.exports = builder;

}).call(this);
